name: Generate Datas

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  build:
    name: Update Data and Deploy
    runs-on: ubuntu-latest
    steps:
      # Step 1: Generate Snake Animation SVG
      - name: Generate Snake Animation
        id: snake-gif
        uses: Platane/snk@master
        with:
          github_user_name: rodolfo-hrosa
          svg_out_path: dist/github-contribution-grid-snake.svg

      # Step 2: Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: gh-pages  # Change to the branch where you want to deploy
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
